server:
  port: 8085

spring:
  application:
    name: reviews-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/reviews?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.angeldevs.reviews_service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
  # Spring Boot Admin Client Configuration
  boot:
    admin:
      client:
        url: ${ADMIN_URL:http://localhost:9090}
        instance:
          service-base-url: ${SERVICE_URL:http://localhost:8085}

documentation:
  application:
    description: "@project.description@"
    version: "@project.version@"

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_HOST:localhost}
    non-secure-port-enabled: false
    secure-port-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
